"""Legacy-method wrapper for Checkpoint 2 hybrid path.

A Phase plugin generated by `make_legacy_phase` delegates `execute()` to a
bound legacy `_phase_<name>` method on the proxy. The legacy method still
operates on the legacy `_RequestContext` shape; the wrapper retrieves it
from `ctx.processed.params['_legacy_ctx']`.

This is intentionally minimal — Checkpoint 2 keeps phase logic where it
lives today and only formalizes registration order via the PhaseGraph.
Checkpoint 3 ports the actual logic into Phase subclasses that consume the
new `RequestContext` directly.
"""

from __future__ import annotations

from typing import Any, Callable

from orchesis.pipeline import Phase, PhaseResult, RequestContext


def make_legacy_phase(
    name: str,
    legacy_method: Callable[[Any], bool],
    *,
    after: tuple[str, ...] = (),
    before: tuple[str, ...] = (),
    appends_tracking: tuple[str, ...] = ("timings",),
    timeout_seconds: float = 5.0,
) -> Phase:
    """Create a Phase instance that wraps a proxy `_phase_<name>` method.

    Args:
        name: phase identifier matching the legacy `"name"` string used by
            `_run_phase_span` so logs and metrics stay aligned.
        legacy_method: bound method like `proxy._phase_parse`. The wrapper
            calls it with the legacy `_RequestContext` retrieved from
            `ctx.processed.params['_legacy_ctx']`.
        after / before: declarative ordering constraints. Should match
            the position the phase historically occupies in proxy.py.
        appends_tracking: tracking-list kinds this phase will append to.
            Default ('timings',) lets the engine record per-phase timing.
        timeout_seconds: per-phase timeout. Legacy methods are synchronous
            and typically fast; default 5s matches proxy defaults.

    Returns:
        A Phase instance ready to register in PhaseRegistry.
    """
    cls_name = "Legacy_" + name.title().replace("_", "") + "Phase"

    async def _execute(self: Phase, ctx: RequestContext) -> PhaseResult:
        legacy_ctx = ctx.processed.params.get("_legacy_ctx")
        if legacy_ctx is None:
            return PhaseResult(
                status="block",
                reason=f"legacy context missing for phase {name!r}",
            )
        method = getattr(self, "_legacy_method", None)
        if method is None:
            return PhaseResult(
                status="block",
                reason=f"legacy method not bound for phase {name!r}",
            )
        try:
            ok = method(legacy_ctx)
        except Exception as e:
            return PhaseResult(
                status="block",
                reason=f"legacy method raised {type(e).__name__}: {e}",
            )
        # Legacy methods historically return bool, but some (e.g.
        # send_response) return None and signal completion implicitly. Treat
        # `None` as success so terminal phases don't get marked as 'block'.
        if ok is None:
            return PhaseResult(status="pass")
        return PhaseResult(status="pass" if ok else "block")

    namespace: dict[str, Any] = {
        "name": name,
        "after": frozenset(after),
        "before": frozenset(before),
        "appends_tracking": frozenset(appends_tracking),
        "timeout_seconds": timeout_seconds,
        "execute": _execute,
    }
    cls = type(cls_name, (Phase,), namespace)
    instance = cls()
    # Store the bound method on the instance — different proxy instances can
    # produce distinct phase instances with different legacy methods.
    instance._legacy_method = legacy_method  # type: ignore[attr-defined]
    return instance
